Repository jfrog/build-info-go, pull requests merged in 2022-09, with the labels that each got.

#100 Fix Nuget requestedBy calculation
  build/maven_test.go
  build/utils/dotnet/solution/solution.go
  build/yarn.go
  entities/buildinfo.go
  go.mod
  go.sum
  utils/fileutils.go
  utils/utils.go
Labels: bug

#103 Add Dotnet module getters, remove redundant setter
  build/dotnet.go
Labels: breaking change

#91 Add support for the Poetry package manager
  build/python.go
  go.mod
  go.sum
  utils/pythonutils/piputils.go
  utils/pythonutils/piputils_test.go
  utils/pythonutils/poetryutils.go
  utils/pythonutils/poetryutils_test.go
  utils/pythonutils/utils.go
  utils/testdata/poetry/nodevdeps/poetry.lock
  utils/testdata/poetry/nodevdeps/pyproject.toml
  utils/testdata/poetry/project/poetry.lock
  utils/testdata/poetry/project/pyproject.toml
Labels: new feature

#107 Improve pip test logs
  build/python_test.go
  utils/pythonutils/piputils_test.go
Labels: ignore for release

#104 Add Poetry Build
  README.md
  build/python.go
  cli/cli.go
  utils/pythonutils/poetryutils.go
  utils/pythonutils/utils.go
Labels: new feature
