Repository jfrog/build-info-go, pull requests merged in 2023-08, with the labels that each got.

#177 Remove deprecated pkg/errors and update dependencies
  build/utils/yarn.go
  cli/cli.go
  entities/buildinfo.go
  go.mod
  go.sum
Labels: ignore for release

#179 Add Frogbot Scan to Repository
  .github/workflows/frogbot-scan-and-fix.yml
  .github/workflows/frogbot-scan-pr.yml
Labels: ignore for release

#172 Build Dependency Tree - Yarn V1
  build/testdata/yarn/project/yarn.lock
  build/testdata/yarn/v1/project/package.json
  build/testdata/yarn/v1/project/yarn.lock
  build/testdata/yarn/v2/project/.yarn/releases/yarn-3.1.1.cjs
  build/testdata/yarn/v2/project/.yarnrc.yml
  build/testdata/yarn/v2/project/package.json
  build/testdata/yarn/v2/project/yarn.lock
  build/utils/npm.go
  build/utils/yarn.go
  build/utils/yarn_test.go
  build/yarn.go
  build/yarn_test.go
  buildinfoschema_test.go
Labels: new feature

#181 Fix npm commands missing standard output
  build/npm.go
  build/utils/npm.go
  build/utils/npm_test.go
  go.mod
  go.sum
Labels: bug

#185 Use Gradle extractor 5 with Gradle >= 6.8.1
  .gitignore
  build/build.go
  build/gradle.go
  build/gradle_test.go
  build/init-gradle-extractor-4.gradle
  build/init-gradle-extractor-5.gradle
  build/testdata/gradle/gradle-6.8.1/.gitattributes
  build/testdata/gradle/gradle-6.8.1/.gitignore
  build/testdata/gradle/gradle-6.8.1/build.gradle
  build/testdata/gradle/gradle-6.8.1/gradle/wrapper/gradle-wrapper.jar
  build/testdata/gradle/gradle-6.8.1/gradle/wrapper/gradle-wrapper.properties
  build/testdata/gradle/gradle-6.8.1/gradlew
  build/testdata/gradle/gradle-6.8.1/gradlew.bat
  build/testdata/gradle/gradle-6.8.1/settings.gradle
  build/testdata/gradle/gradle-6.8/.gitattributes
  build/testdata/gradle/gradle-6.8/.gitignore
  build/testdata/gradle/gradle-6.8/build.gradle.kts
  build/testdata/gradle/gradle-6.8/gradle/wrapper/gradle-wrapper.jar
  build/testdata/gradle/gradle-6.8/gradle/wrapper/gradle-wrapper.properties
  build/testdata/gradle/gradle-6.8/gradlew
  build/testdata/gradle/gradle-6.8/gradlew.bat
  build/testdata/gradle/gradle-6.8/settings.gradle.kts
  build/testdata/gradle/gradle-7.0/.gitattributes
  build/testdata/gradle/gradle-7.0/.gitignore
  build/testdata/gradle/gradle-7.0/build.gradle.kts
  build/testdata/gradle/gradle-7.0/gradle/wrapper/gradle-wrapper.jar
  build/testdata/gradle/gradle-7.0/gradle/wrapper/gradle-wrapper.properties
  build/testdata/gradle/gradle-7.0/gradlew
  build/testdata/gradle/gradle-7.0/gradlew.bat
  build/testdata/gradle/gradle-7.0/settings.gradle.kts
Labels: improvement

#186 Update Gradle init script
  build/init-gradle-extractor-5.gradle
Labels: ignore for release

#187 Fix release script
  release/pipelines.yml
Labels: ignore for release

#188 Keep file permissions when copy directory
  go.mod
  go.sum
  utils/fileutils.go
Labels: ignore for release

#189 Update Gradle extractor to 5.1.5
  build/gradle.go
Labels: improvement
