Repository jfrog/build-info-go, pull requests merged in 2023-09, with the labels that each got.

#191 Updating NuGet solution file
  build/utils/dotnet/solution/solution.go
Labels: ignore for release

#192 Update Maven and Gradle extractors
  build/gradle.go
  build/maven.go
Labels: improvement

#193 Fix release script
  .github/workflows/test.yml
  go.mod
  go.sum
  release/pipelines.yml
Labels: ignore for release

#195 Add Shellcheck action and fix issues
  .github/workflows/analysis.yml
  buildscripts/build.sh
  release/build.sh
  utils/goutils.go
Labels: ignore for release

#196 Improve fileutils error handling
  utils/fileutils.go
Labels: ignore for release

#198 Parse Gradle versions even if strerr is not empty
  build/gradle.go
Labels: bug

#199 Improve npm logs
  build/utils/npm.go
Labels: improvement
