Repository jfrog/build-info-go, pull requests merged in 2023-05, with the labels that each got.

#155 Add maven command logs
  .github/workflows/analysis.yml
  build/maven.go
  build/python.go
Labels: improvement

#140 Generate build-info on release
  release/pipelines.yml
Labels: ignore for release

#158 Update dependencies
  go.mod
  go.sum
Labels: ignore for release

#159 Fix Maven home parsing for paths with whitespaces
  build/maven.go
  build/maven_test.go
Labels: bug

#162 Update extractors to build-info-extractor 2.40.0 / gradle-artifactory-plugin 4.32.0
  build/gradle.go
  build/maven.go
Labels: improvement

#141 Support executing npm commands
  README.md
  build/npm.go
  build/npm_test.go
  build/utils/npm.go
  build/utils/npm_test.go
  buildinfoschema_test.go
  cli/cli.go
Labels: improvement

#166 Avoid running tests and static analysis on tags
  .github/workflows/analysis.yml
  .github/workflows/test.yml
Labels: ignore for release
