Repository jfrog/build-info-go, pull requests merged in 2023-12, with the labels that each got.

#220 Update Maven and Gradle extractors
  build/gradle.go
  build/maven.go
Labels: improvement

#221 Refine audit
  .jfrog/jfrog-apps-config.yml
  release/pipelines.yml
Labels: ignore for release

#219 Handle Gradle system properties with spaces
  build/gradle.go
  build/gradle_test.go
Labels: bug

#222 Gradle - fix command properties recognition
  build/gradle.go
  build/gradle_test.go
Labels: bug

#223 Update dependencies
  go.mod
  go.sum
Labels: ignore for release

#224 Update Maven Build-info extractor to 2.41.9
  build/maven.go
Labels: improvement

#225 Gradle - add quotes if needed to system properties
  build/gradle.go
  build/gradle_test.go
Labels: bug

#226 Fix Nuget nuspec files UTF-16 encoding issue
  build/utils/dotnet/dependencies/packagesconfig.go
  build/utils/dotnet/dependencies/testdata/packagesproject/localcache/id2/2.0.0/id2.nuspec
Labels: bug
