Repository jfrog/build-info-go, pull requests merged in 2023-11, with the labels that each got.

#209 Fix Maven/Gradle Artifacts build.timestamp property
  build/build.go
  build/gradle.go
  build/maven.go
  build/service.go
  buildinfoschema_test.go
  utils/dependenciesutils.go
Labels: bug

#211 Promote dependencies for release
  build/gradle.go
  build/maven.go
  go.mod
  go.sum
Labels: ignore for release

#212 Yarn - Deleting error message & test for a deprecated issue
  build/utils/yarn.go
  build/utils/yarn_test.go
Labels: improvement

#213 Python log parser - handle limited size log content
  utils/pythonutils/utils.go
  utils/pythonutils/utils_test.go
Labels: bug

#214 Remove poetry implementation
  README.md
  build/python.go
  cli/cli.go
  utils/pythonutils/poetryutils.go
  utils/pythonutils/utils.go
Labels: bug

#215 Changing Solution methods + fixing variables names
  build/utils/dotnet/solution/solution.go
Labels: improvement

#216 Possible race condition when running commands
  go.mod
  go.sum
  utils/command.go
  utils/goutils.go
  utils/pythonutils/pipenvutils.go
  utils/pythonutils/piputils.go
  utils/pythonutils/utils.go
Labels: bug
