Repository jfrog/build-info-go, pull requests merged in 2024-02, with the labels that each got.

#231 Fix Nupkg/Nuspec UTF-16 encoding and support uppercase dependencies
  .github/workflows/analysis.yml
  .github/workflows/frogbot-scan-and-fix.yml
  .github/workflows/test.yml
  build/utils/dotnet/dependencies/packagesconfig.go
  build/utils/dotnet/dependencies/packagesconfig_test.go
  build/utils/dotnet/dependencies/testdata/packagesproject/localcache/Microsoft.Web.Infrastructure/1.0.0.0/Microsoft.Web.Infrastructure.1.0.0.0.nupkg
  build/utils/dotnet/dependencies/testdata/packagesproject/localcache/Microsoft.Web.Infrastructure/1.0.0.0/Microsoft.Web.Infrastructure.nuspec
  build/utils/dotnet/dependencies/testdata/packagesproject/localcache/id2/2.0.0/id2.nuspec
  build/utils/dotnet/dependencies/testdata/packagesproject/packages.config
  go.mod
  go.sum
Labels: bug

#234 Update Maven and Gradle extractors
  build/gradle.go
  build/maven.go
Labels: improvement

#235 Fix Nuget uppercase modules cache issue
  build/utils/dotnet/dependencies/packagesconfig.go
  build/utils/dotnet/dependencies/testdata/packagesproject/localcache/microsoft.web.infrastructure/1.0.0.0/microsoft.web.infrastructure.1.0.0.0.nupkg
  build/utils/dotnet/dependencies/testdata/packagesproject/localcache/microsoft.web.infrastructure/1.0.0.0/microsoft.web.infrastructure.nuspec
Labels: bug

#232 Modify GetFileChecksums to receive the algorithms
  build/golang.go
  build/utils/npm.go
  utils/checksum.go
  utils/checksum_test.go
  utils/fileutils.go
Labels: ignore for release

#233 Add exclude pattern for dotnet
  build/dotnet.go
  build/utils/dotnet/solution/solution.go
  build/utils/dotnet/solution/solution_test.go
Labels: improvement
