Repository jfrog/build-info-go, pull requests merged in 2024-09, with the labels that each got.

#270 Export CreateAlternativeVersionForms function
  build/utils/dotnet/dependencies/packagesconfig.go
  build/utils/dotnet/dependencies/packagesconfig_test.go
Labels: improvement

#274 Update dependencies
  go.mod
  go.sum
Labels: ignore for release

#258 Deterministic cyclonedx output
  entities/buildinfo.go
  entities/buildinfo_test.go
Labels: bug

#276 Add twine support
  README.md
  build/build.go
  build/golang.go
  build/npm.go
  build/python.go
  build/yarn.go
  cli/cli.go
  utils/pythonutils/piputils.go
  utils/pythonutils/piputils_test.go
  utils/pythonutils/poetryutils.go
  utils/pythonutils/poetryutils_test.go
  utils/pythonutils/pyprojectutils.go
  utils/pythonutils/pyprojectutils_test.go
  utils/pythonutils/twineutils.go
  utils/pythonutils/twineutils_test.go
  utils/pythonutils/utils.go
  utils/testdata/pip/pyproject/pyproject.toml
Labels: new feature

#273 Fix npm's deployment path
  build/utils/npm.go
  build/utils/npm_test.go
Labels: bug

#277 Skip install in dependencies map calculation if requested
  build/testdata/npm/noBuildProject/package.json
  build/utils/npm.go
  build/utils/npm_test.go
  utils/error.go
Labels: improvement
